server:
  port: 8092

spring:
  profiles:
    active: @activeProfile@
    # PROD execute: mvn clean package -P prod

  # Desabilitar página de login padrão
  security:
    user:
      name: none
      password: none